### ISSUE TITLE
New release after #8

### ISSUE THREAD

**Issue by Janno** [FloppyDisck/SHT31-rs#10]
It would be great if there was a released version that included #8. I spent a few days trying to debug my code and finally managed to spot the problem with the help of a logic analyzer.

P.S.: Thanks so much for building the library!

**Comment by haraldkubota** [comment]
Can confirm: v0.3.1 works where v0.3.0 did not. Tested on RP2040 with Embassy. And it even works via a PCA9548A (I2C switch). Please release as a crate as

`sht31 = { git = "https://github.com/FloppyDisck/SHT31-rs.git", branch = "main" }` does not look as nice as `sht31 = "0.3.1"`
